// Generated by Wrangler on Tue May 21 2024 18:55:27 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	USERS: KVNamespace;
	ENVIRONMENT: string;
	PROJECT: DurableObjectNamespace<Project>;
	STATES: R2Bucket;
}
