#:schema node_modules/wrangler/config-schema.json
name = "tfstate-edge"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[[routes]]
# TODO replace with your domain
pattern = "tfstate-edge.example.com"
custom_domain = true

[vars]
ENVIRONMENT = "production"

[[durable_objects.bindings]]
name = "PROJECT"
class_name = "Project"

[[migrations]]
tag = "v1"
new_classes = ["Project"]

[[kv_namespaces]]
binding = "USERS"
# TODO replace with your KV namespace
id = "1ac1307371a84b1abc744b9581ee9f9e"

[[r2_buckets]]
binding = "STATES"
# TODO replace with your R2 bucket
bucket_name = "tfstate-edge-states"
